# Generated by Django 4.0.3 on 2022-03-08 20:45

from django.db import migrations
from django.utils.text import slugify
from books import categories as category_data


def create_categories(apps, schema_editor):
    Category = apps.get_model("books", "Category")
    for category_name in category_data.categories:
        Category.objects.create(name=category_name, slug=slugify(category_name))


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_alter_book_category"),
    ]

    operations = [migrations.RunPython(create_categories)]
