# Generated by Django 4.0.3 on 2022-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20220308_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
