# Generated by Django 4.0.3 on 2022-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
