# Generated by Django 4.0.3 on 2022-03-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20220308_2045'),
        ('books', '0014_alter_book_favorite'),
    ]

    operations = [
    ]
