# Generated by Django 4.0.3 on 2022-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
