# Generated by Django 4.0.3 on 2022-03-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_merge_20220308_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
