# Generated by Django 4.0.3 on 2022-03-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_favorite_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
