# Generated by Django 4.0.3 on 2022-03-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_favorite_date'),
        ('books', '0019_alter_book_favorited_number'),
    ]

    operations = [
    ]
