# Generated by Django 4.0.3 on 2022-03-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_favorited_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorited_number',
            field=models.IntegerField(default=0),
        ),
    ]
