# Generated by Django 4.0.3 on 2022-03-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_favorite_date'),
        ('books', '0025_comment_user'),
    ]

    operations = [
    ]
